lanquage: python

install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
services:
  - docker
deploy:
  provider: heroku
  app: infinite-reaches-64324
  api_key: ${HEROKU_API_KEY}